#+author: conao3
#+date: <2020-03-20 Fri>

[[https://github.com/conao3/dired-lsi.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/dired-lsi.el.png]]
[[https://github.com/conao3/dired-lsi.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/dired-lsi.el.svg?style=flat-square]]
[[https://github.com/conao3/dired-lsi.el/releases][https://img.shields.io/github/tag/conao3/dired-lsi.el.svg?style=flat-square]]
[[https://github.com/conao3/dired-lsi.el/actions][https://github.com/conao3/dired-lsi.el/workflows/Main%20workflow/badge.svg]]
[[https://app.codacy.com/project/conao3/dired-lsi.el/dashboard][https://img.shields.io/codacy/grade/62a36f4f04524d5e8c758440e8071c45.svg?logo=codacy&style=flat-square]]
[[https://www.patreon.com/conao3][https://img.shields.io/badge/patreon-become%20a%20patron-orange.svg?logo=patreon&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://conao3-support.slack.com/join/shared_invite/enQtNjUzMDMxODcyMjE1LWUwMjhiNTU3Yjk3ODIwNzAxMTgwOTkxNmJiN2M4OTZkMWY0NjI4ZTg4MTVlNzcwNDY2ZjVjYmRiZmJjZDU4MDE][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Table of Contents
- [[#description][Description]]
- [[#install][Install]]
- [[#usage][Usage]]
- [[#customize][Customize]]
- [[#information][Information]]
  - [[#community][Community]]
  - [[#contribution][Contribution]]
  - [[#migration][Migration]]
  - [[#license][License]]
  - [[#author][Author]]
  - [[#contributors][Contributors]]

* Description
Add memo to directory and show it in dired.

This package is dired client for [[https://github.com/ShotaroKataoka/ls-Improved][ls-Improved]], but it also work standalone.

* Install
#+begin_src emacs-lisp
  (leaf dired-lsi
    :ensure t
    :hook dired-mode-hook)
#+end_src

If you use [[https://github.com/conao3/dired-git.el][dired-git]], I suggest below customize.

#+begin_src emacs-lisp
  (leaf dired-lsi
    :ensure t
    :custom ((dired-lsi--create-spacer-fn
              . (lambda () (when all-the-icons-dired-mode "  \t"))))
    :hook dired-mode-hook)
#+end_src

* Usage
Enable ~dired-lsi-mode~ in dired buffer.

You can edit folder description via below functions.

- dired-lsi-add-description :: In dired, add description for directory on this line.
- dired-lsi-mkdir-with-description :: Make directory with description.

Or, Add/Edit ~.description.lsi~ directly to modify folder description.
See [[https://github.com/ShotaroKataoka/ls-Improved#usage][Usage - ls-Improved]].

After edit ~.description.lsi~, please revert dired buffer
(In dired buffer, ~M-x dired-revert (g)~) to reflect the change.

* Customize
- dired-lsi-separator :: Separetor between item and description.
- dired-lsi--create-spacer-fn :: Create additional spacer function.

  This variable shuold be function symbol or lambda function.
  That function called with empty argument and should return string or nil.

* Information
** Community
All feedback and suggestions are welcome!

You can use github issues, but you can also use [[https://conao3-support.slack.com/join/shared_invite/enQtNjUzMDMxODcyMjE1LWUwMjhiNTU3Yjk3ODIwNzAxMTgwOTkxNmJiN2M4OTZkMWY0NjI4ZTg4MTVlNzcwNDY2ZjVjYmRiZmJjZDU4MDE][Slack]]
if you want a more casual conversation.

** Contribution
We welcome PR!

*** Require tools for testing
- keg
  #+begin_src shell
    cd ~/
    hub clone conao3/keg .keg
    export PATH="$HOME/.keg/bin:$PATH"
  #+end_src

*** Running test
Below operation flow is recommended.
#+begin_src shell
  git branch [feature-branch]       # Create branch named [feature-branch]
  git checkout [feature-branch]     # Checkout branch named [feature-branch]

  # <edit loop>
  emacs dired-lsi.el             # Edit something you want

  make test                         # Test dired-lsi
  git commit -am "brabra"           # Commit (auto-run test before commit)
  # </edit loop>

  hub fork                          # Create fork at GitHub
  git push [user] [feature-branch]  # Push feature-branch to your fork
  hub pull-request                  # Create pull-request
#+end_src

** Migration

** License
#+begin_example
  General Public License Version 3 (GPLv3)
  Copyright (c) Naoya Yamashita - https://conao3.com
  https://github.com/conao3/dired-lsi.el/blob/master/LICENSE
#+end_example

** Author
- Naoya Yamashita ([[https://github.com/conao3][conao3]])

** Contributors

